### ISSUE TITLE
Add widget testing

### ISSUE THREAD

**Issue by avmarchenko** [exa-analytics/exawidgets#6]
**Edit:** See the second comment, this comment is left for historical purposes.

It would be helpful if we had an integration to test the execution and loading of a notebook widget within the jupyter notebook on multiple platforms and web browsers. I found [sauce labs](https://saucelabs.com/) which may (or may not) do this kind of thing. An immediate complication is that it isn't as simple as run some JS code on loading an html page but rather, more like, on page load, make a call to the notebook's JS to run a cell which will callback to the notebook's ipywidgets JS framework which will load the notebook extension which should then somehow return a success or failure.

**Comment by avmarchenko** [comment]
We could alternatively explore a solution where we execute a "demo" notebook or "test" notebook with cells containing commands that write some type of output report that can then be checked by a simple unittest function. The `nbconvert` function can execute notebooks as can the [runipy](https://github.com/paulgb/runipy) package.

I not sure of the strength of `runipy` because it doesn't load the ipython kernel (perhaps it can somehow?). This seems to work:
```
jupyter nbconvert --exec execme.ipynb
```
Which writes an "output" file `tmp` that contains the result of a bidirectional communication perfromed within the ipywidgets framework.

[execme.zip](https://github.com/exa-analytics/exawidgets/files/892005/execme.zip)

**Comment by tjduigna** [comment]
This sounds promising, we can even just work in a custom message to be passed back on successful "load" of the widget to start for something simple.
